name: qr_reader
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  barras: ^0.0.2
  flutter_styled_toast: ^1.5.0+1
  validated: ^1.0.3
  url_launcher: ^5.7.10
  adaptive_theme: ^1.1.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
